// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Board = (function(_super) {
    __extends(Board, _super);

    function Board() {
      _ref = Board.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Board.prototype.defaults = {
      spaces: [null, null, null, null, null, null, null, null, null]
    };

    Board.prototype.setSpace = function(space_index, player_marker) {
      var spaces;

      spaces = this.get('spaces');
      spaces[space_index] = player_marker;
      return this.set({
        spaces: spaces
      });
    };

    Board.prototype.save = function() {
      return console.log('lol');
    };

    return Board;

  })(Backbone.Model);

}).call(this);
