// Generated by CoffeeScript 1.6.2
(function() {
  describe('Board', function() {
    var board;

    board = null;
    beforeEach(function() {
      board = new Board;
      return board.clear();
    });
    it('constructs a Board object', function() {
      return expect(board).not.toBe(null);
    });
    it('has a spaces array, filled with nulls', function() {
      return expect(board.get('spaces')).toEqual([null, null, null, null, null, null, null, null, null]);
    });
    it('sets a marker on a board with a given index', function() {
      board.setSpace(1, 'x');
      expect(board.get('spaces')).toEqual([null, 'x', null, null, null, null, null, null, null]);
      board.clear();
      return expect(board.get('spaces')).toEqual([null, null, null, null, null, null, null, null, null]);
    });
    return it('checks to see if a space is open', function() {
      return expect(board.spaceOpen(1)).toEqual(true);
    });
  });

}).call(this);
