// Generated by CoffeeScript 1.6.2
(function() {
  describe('ConfigView', function() {
    var configView, game;

    configView = null;
    game = null;
    beforeEach(function() {
      game = new Game;
      return configView = new ConfigView({
        model: game
      });
    });
    return it('instantiates a ConfigView', function() {
      return expect(configView).not.toBe(null);
    });
  });

}).call(this);
