// Generated by CoffeeScript 1.6.2
(function() {
  describe('Calculator', function() {
    return it('can add two positive numbers', function() {
      var calculator, result;

      calculator = new Calculator();
      result = calculator.add(2, 3);
      return expect(result).toBe(5);
    });
  });

}).call(this);
