// Generated by CoffeeScript 1.6.2
(function() {
  describe('Players', function() {
    return it('constructs a Players object', function() {
      return expect(new Players).not.toBe(null);
    });
  });

}).call(this);
